/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bovw_native_handler */

#ifndef _Included_bovw_native_handler
#define _Included_bovw_native_handler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bovw_native_handler
 * Method:    getDatahistogram
 * Signature: (JJI)[F
 */
JNIEXPORT jfloatArray JNICALL Java_bovw_native_1handler_getDatahistogram
  (JNIEnv *, jclass, jlong, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
